/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-08-08 14:56:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/../WEB-INF/all_component/footer.jsp", Long.valueOf(1691506576325L));
    _jspx_dependants.put("/../WEB-INF/all_component/allCss.jsp", Long.valueOf(1691500903194L));
    _jspx_dependants.put("/../WEB-INF/all_component/Navbar.jsp", Long.valueOf(1691506612374L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Ebook: Index</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".back-img {\r\n");
      out.write("	background: url(\"img/books.jpg\");\r\n");
      out.write("	height: 50vh;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-repeat: repeat;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-position: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".crd-ho {\r\n");
      out.write("	background-color: #fcf7f7;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #f7f7f7\">\r\n");
      out.write("	");
      out.write("<div class=\"container-fluid p-3 bg-light\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-3 text-success\">\r\n");
      out.write("<h3><i class=\"fas fa-book\"></i> Ebooks</h3>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-6\">\r\n");
      out.write("<form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("      <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("      <button class=\"btn btn-primary my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-3\">\r\n");
      out.write("<a href=\"\"class=\"btn btn-success\">Login</a>\r\n");
      out.write("<a href = \"\" class=\"btn btn-primary text-white\">Register</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-primary\">\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\"><i class=\"fas fa-home\"></i></a>\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\">Home <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("       <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link disabled\" href=\"#\"> <i class=\"fas fa-book-open\"></i> Recent Book</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\"><i class=\"fas fa-book-open\"></i> New Book</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link disabled\" href=\"#\"><i class=\"fas fa-book-open\"></i> Old Book</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("           <button class=\"btn btn-light my-2 my-sm-0\" type=\"submit\"><i class=\"fas fa-cog\"></i> Setting</button>\r\n");
      out.write("      <button class=\"btn btn-light my-2 my-sm-0 ml-1\" type=\"submit\"><i class=\"fas fa-phone-square-alt\"></i> Contact Us</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("	<div class=\"container-fluid back-img\">\r\n");
      out.write("		<h1 class=\"text-center text-light\">EBook Management System</h1>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Recent book module -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h3 class=\"text-center\">Recent Book</h3>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"img/node-js.jpg\"\r\n");
      out.write("							style=\"width: 150px, height:200px\" class=\"img-thumblin\" />\r\n");
      out.write("						<p>Node-js Framework</p>\r\n");
      out.write("						<p>Emanuele Delbond</p>\r\n");
      out.write("						<p>Categories: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm\"><i class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-success btn-sm ml-1\"> View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm ml-1\"> 299</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"img/node-js.jpg\"\r\n");
      out.write("							style=\"width: 150px, height:200px\" class=\"img-thumblin\" />\r\n");
      out.write("						<p>Node-js Framework</p>\r\n");
      out.write("						<p>Emanuele Delbond</p>\r\n");
      out.write("						<p>Categories: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm\"><i class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-success btn-sm ml-1\"> View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm ml-1\"> 299</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"img/node-js.jpg\"\r\n");
      out.write("							style=\"width: 150px, height:200px\" class=\"img-thumblin\" />\r\n");
      out.write("						<p>Node-js Framework</p>\r\n");
      out.write("						<p>Emanuele Delbond</p>\r\n");
      out.write("						<p>Categories: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm\"><i class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-success btn-sm ml-1\"> View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm ml-1\"> 299</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"img/node-js.jpg\"\r\n");
      out.write("							style=\"width: 150px, height:200px\" class=\"img-thumblin\" />\r\n");
      out.write("						<p>Node-js Framework</p>\r\n");
      out.write("						<p>Emanuele Delbond</p>\r\n");
      out.write("						<p>Categories: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm\"><i class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-success btn-sm ml-1\"> View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm ml-1\"> 299</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"text-center mt-1\">\r\n");
      out.write("			<a href=\"\" class=\"btn btn-danger btn-sm text-white\">View All</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--  End of Recent Book Module -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- New book module -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h3 class=\"text-center\">New Book</h3>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"img/node-js.jpg\"\r\n");
      out.write("							style=\"width: 150px, height:200px\" class=\"img-thumblin\" />\r\n");
      out.write("						<p>Node-js Framework</p>\r\n");
      out.write("						<p>Emanuele Delbond</p>\r\n");
      out.write("						<p>Categories: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm\"><i class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-success btn-sm ml-1\"> View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm ml-1\"> 299</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"img/node-js.jpg\"\r\n");
      out.write("							style=\"width: 150px, height:200px\" class=\"img-thumblin\" />\r\n");
      out.write("						<p>Node-js Framework</p>\r\n");
      out.write("						<p>Emanuele Delbond</p>\r\n");
      out.write("						<p>Categories: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm\"><i class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-success btn-sm ml-1\"> View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm ml-1\"> 299</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"img/node-js.jpg\"\r\n");
      out.write("							style=\"width: 150px, height:200px\" class=\"img-thumblin\" />\r\n");
      out.write("						<p>Node-js Framework</p>\r\n");
      out.write("						<p>Emanuele Delbond</p>\r\n");
      out.write("						<p>Categories: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm\"><i class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-success btn-sm ml-1\"> View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm ml-1\"> 299</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"img/node-js.jpg\"\r\n");
      out.write("							style=\"width: 150px, height:200px\" class=\"img-thumblin\" />\r\n");
      out.write("						<p>Node-js Framework</p>\r\n");
      out.write("						<p>Emanuele Delbond</p>\r\n");
      out.write("						<p>Categories: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm\"><i class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-success btn-sm ml-1\"> View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm ml-1\"> 299</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"text-center mt-1\">\r\n");
      out.write("			<a href=\"\" class=\"btn btn-danger btn-sm text-white\">View All</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--  End of New Book Module -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Old book module -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h3 class=\"text-center\">Old Book</h3>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"img/node-js.jpg\"\r\n");
      out.write("							style=\"width: 150px, height:200px\" class=\"img-thumblin\" />\r\n");
      out.write("						<p>Node-js Framework</p>\r\n");
      out.write("						<p>Emanuele Delbond</p>\r\n");
      out.write("						<p>Categories: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-success btn-sm ml-5\"> View Details</a>\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm ml-1\"> 299</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"img/node-js.jpg\"\r\n");
      out.write("							style=\"width: 150px, height:200px\" class=\"img-thumblin\" />\r\n");
      out.write("						<p>Node-js Framework</p>\r\n");
      out.write("						<p>Emanuele Delbond</p>\r\n");
      out.write("						<p>Categories: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-success btn-sm ml-5\"> View Details</a>\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm ml-1\"> 299</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"img/node-js.jpg\"\r\n");
      out.write("							style=\"width: 150px, height:200px\" class=\"img-thumblin\" />\r\n");
      out.write("						<p>Node-js Framework</p>\r\n");
      out.write("						<p>Emanuele Delbond</p>\r\n");
      out.write("						<p>Categories: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-success btn-sm ml-5\"> View Details</a>\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm ml-1\"> 299</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card crd-ho\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img alt=\"\" src=\"img/node-js.jpg\"\r\n");
      out.write("							style=\"width: 150px, height:200px\" class=\"img-thumblin\" />\r\n");
      out.write("						<p>Node-js Framework</p>\r\n");
      out.write("						<p>Emanuele Delbond</p>\r\n");
      out.write("						<p>Categories: New</p>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<a href=\"\" class=\"btn btn-success btn-sm ml-5\"> View Details</a>\r\n");
      out.write("							<a href=\"\" class=\"btn btn-danger btn-sm ml-1\"> 299</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"text-center mt-1\">\r\n");
      out.write("			<a href=\"\" class=\"btn btn-danger btn-sm text-white\">View All</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--  End of Old Book Module -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"footer bg-primary py-3\">\r\n");
      out.write("    <div class=\"container text-center\">\r\n");
      out.write("        <h5 class=\"mb-3 text-white\">Website Designed and Developed by <a class=\"text-white\" href=\"http://your-website.com\">Rohit Kumar</a>, a Full-Stack Web Developer</h5>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Social Media Icons -->\r\n");
      out.write("        <div>\r\n");
      out.write("            <a href=\"#\" class=\"text-white me-2\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("            <a href=\"#\" class=\"text-white me-2\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("            <a href=\"#\" class=\"text-white me-2\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("            <a href=\"#\" class=\"text-white me-2\"><i class=\"fab fa-linkedin\"></i></a>\r\n");
      out.write("            <a href=\"#\" class=\"text-white me-2\"><i class=\"fab fa-github\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Copyright -->\r\n");
      out.write("        <div class=\"text-white mt-2\">\r\n");
      out.write("            <small>© 2023 Rohit Kumar. All rights reserved.</small>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
